import { FC } from "react";
import axios from "axios";

// interface pageProps {}

export const revalidate = 10;

const page = async ({}) => {
  //   const res = await fetch("https://jsonplaceholder.typicode.com/posts/1", {
  //     // cache: "no-store" // no cache means refetch means not static
  //     next: { revalidate: 10 }, //10seconds
  //   });
  //   const data = await res.json();
  const { data } = await axios.get(
    "https://jsonplaceholder.typicode.com/posts/1"
  );
  return <div>{JSON.stringify(data)}</div>;
};

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default page;
