import React from "react";

const page = () => {
  return <div>Contact Page</div>;
};

export const metadata = {
  title: "Contact",
  description: "Generated by create next app",
};

export default page;
