export const metadata = {
  title: "About",
  description: "Generated by create next app",
};

export default function AboutLayout({
  children, // will be a page or nested layout
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="p-4">
      {/* Include shared UI here e.g. a header or sidebar */}
      <nav>Posts Data from jsonplaceholder api</nav>

      {children}
    </section>
  );
}
