import { FC } from "react";

interface pageProps {
  params: {
    postid: string;
  };
}

//to make this route server side generated, we need to generate static params
export async function generateStaticParams() {
  const posts = ["post-one", "post-two", "post-three"];

  return posts.map((post) => {
    return {
      postId: post,
    };
  });
}
// const page = async (props: any) => {
//   // console.log(props);

//   // db fetching
//   //   const res = await fetch(
//   //     `https://jsonplaceholder.typicode.com/posts/${params.postid}`
//   //   );

//   return <div></div>;
// };

// export default page;

// server component
const page = async ({ params }: pageProps) => {
  //   console.log(props);

  // db fetching
  //   const res = await fetch(
  //     `https://jsonplaceholder.typicode.com/posts/${params.postid}`
  //   );

  return <div>post {params.postid}</div>;
};

export const metadata = {
  title: "Posts",
  description: "Generated by create next app",
};

export default page;
